# Generated by Django 4.0.4 on 2022-04-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
    ]
