# Generated by Django 4.0.4 on 2022-04-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_remove_task_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
