# Generated by Django 4.0.4 on 2022-04-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_assignment_standard_submission_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
    ]
