# Generated by Django 4.0.4 on 2022-04-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_remove_student_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
