# Generated by Django 4.0.4 on 2022-04-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_remove_students_id_alter_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='standard',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='classroom.standard'),
        ),
    ]
