# Generated by Django 4.0.4 on 2022-04-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_alter_students_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_student',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='classroom.standard'),
            preserve_default=b'I01\n',
        ),
    ]
