# Generated by Django 4.0.4 on 2022-04-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_user_class_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='class_student',
            new_name='standard',
        ),
    ]
