# Generated by Django 4.0.4 on 2022-04-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_rename_class_student_user_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.standard'),
            preserve_default=False,
        ),
    ]
