# Generated by Django 4.0.4 on 2022-04-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_assignment_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='creator',
        ),
    ]
