# Generated by Django 4.0.4 on 2022-04-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_assignment_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
