# Generated by Django 4.0.4 on 2022-04-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_alter_assignment_deadline_alter_assignment_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='post_time',
            field=models.CharField(max_length=100),
        ),
    ]
